# Generated by Django 4.1.2 on 2022-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
